import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url);
const ui=require('../app/src/main/assets/hylink-presentation.js');
const now=Date.parse('2026-09-10T07:00:00Z');
let passed=0;
function check(name,fn){fn();passed++;console.log('PASS',name);}
const state={updated_at:new Date(now-10000).toISOString(),onroad:0,ignition:0};
const summary=(s=state,raw={},opts={})=>ui.summary(s,raw,{now,hasKey:true,...opts});
check('missing numeric values are not zero',()=>{for(const value of [null,undefined,'',' ',false,true,'bad'])assert.equal(ui.number(value),null)});
check('real zero remains zero',()=>{assert.equal(ui.number(0),0);assert.equal(ui.number('0'),0)});
check('no data is not parked',()=>assert.equal(summary({}).status,'확인 대기'));
check('first install explains linking',()=>assert.equal(summary({}, {}, {hasKey:false}).condition,'unlinked'));
check('explicit parked state',()=>assert.equal(summary().status,'주차 중'));
check('onroad and ignition states',()=>{assert.equal(summary({...state,onroad:1}).status,'주행 중');assert.equal(summary({...state,ignition:1}).status,'시동 켜짐')});
check('missing ignition is not parked',()=>assert.equal(summary({updated_at:state.updated_at,onroad:0}).status,'상태 확인 중'));
check('onroad stale after 60s',()=>assert.equal(summary({...state,onroad:1,updated_at:new Date(now-61000).toISOString()}).condition,'stale'));
check('offroad heartbeat remains recent for 15min',()=>{assert.equal(summary({...state,updated_at:new Date(now-600000).toISOString()}).condition,'recent');assert.equal(summary({...state,updated_at:new Date(now-901000).toISOString()}).condition,'stale')});
check('network failure preserves history but warns',()=>{const result=summary(state,{}, {error:true});assert.equal(result.condition,'error');assert.match(result.description,/마지막 수신/) });
check('future or invalid timestamp does not claim freshness',()=>{for(const updated_at of ['invalid',new Date(now+120000).toISOString()])assert.equal(summary({...state,updated_at}).fresh,'unknown')});
const luminance=hex=>{const c=hex.match(/\w\w/g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722};
const contrast=(a,b)=>{const [hi,lo]=[luminance(a),luminance(b)].sort((a,b)=>b-a);return(hi+.05)/(lo+.05)};
check('body and secondary text meet 4.5:1 on all primary surfaces',()=>{for(const foreground of ['f3f4f6','b2b7bf','a1a7b0'])for(const background of ['101113','191b1e','222529','2b2e33'])assert.ok(contrast(foreground,background)>=4.5,`${foreground}/${background}`)});
check('action and warning text contrast',()=>{assert.ok(contrast('21150c','ff9b54')>=4.5);assert.ok(contrast('ffe0ae','30291e')>=4.5)});
const html=fs.readFileSync(new URL('../app/src/main/assets/main.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../app/src/main/assets/hylink-refinement.css',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../app/src/main/assets/hylink.js',import.meta.url),'utf8');
check('document IDs are unique',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size)});
check('scalable text and motion accommodation',()=>{assert.ok(!html.includes('user-scalable=no'));assert.match(css,/prefers-reduced-motion/);assert.match(css,/body\.large-text/)});
check('trip shortcut has a real section target',()=>{assert.match(html,/id="drive-reports"/);assert.match(html,/data-section="drive-reports"/);assert.match(js,/button\.dataset\.section/)});
check('no decorative animated locator',()=>assert.ok(!js.includes('leaflet-vehicle-ripple')));
console.log(`${passed} UX checks passed`);
